version: '3.7'

services:
  lll-web-ui-dev:
    build: .
    image: avrc26/lll-web-ui:D2.0a
    container_name: lll-web-ui-dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 9000:8000
    # env_file:
    #   - ./.env.dev
    networks: 
      - avrc26-apps-dev
networks:
  avrc26-apps-dev:
    external: true